ManageIQ/manageiq-messaging

lib/manageiq-messaging.rb, lib/manageiq/messaging/background_job.rb, lib/manageiq/messaging/client.rb, lib/manageiq/messaging/common.rb, lib/manageiq/messaging/queue.rb, lib/manageiq/messaging/stomp_client.rb, lib/manageiq/messaging/topic.rb
`ManageIQ::Messaging::Client.open(options)` returns a client object that is used to send or receive messages. This allows to swap the actual client implementation. Currently STOMP client is the only implementation, to be replaced by an AMQP client soon.
```
client.publish_message(options)
client.publish_topic(options)
client.publish_messages(messages)
```
A client can publish either a message (1-to-1) or a topic (1-to-many). `client.publish_messages` is a batch send. It is not just a convenience method but may help the performance. It is not manifested with STOMP client, but an AMQP client it can accumulate multiple messages and finish with one send.
We can argue whether to provide a `client.publish_topics` method. I don't see it is common when something happens a provider needs to …
=> Client public interface

manageiq-messaging.gemspec
Remove remnants from a merge conflict in the gemspec preventing `gem install`
```
/home/agrare/.bundle/ruby/2.3.0/manageiq-messaging-68211e634430/manageiq-messaging.gemspec:32: syntax error, unexpected ===, expecting keyword_end
=======
^. Bundler cannot continue.
>  <<<<<<< 4fd654fd133243bafddbffeb6eda7cd4f2b8ba57
```
=> Fix merge of manageiq-messaging.gemspec

lib/manageiq/messaging/background_job.rb, lib/manageiq/messaging/client.rb, lib/manageiq/messaging/common.rb, lib/manageiq/messaging/queue.rb, lib/manageiq/messaging/stomp_client.rb
If the `client.publish_message` has a block, consider the message requires a response from the subscriber and the block will be executed upon receiving the response.
The typical usage is
```
client.publish_message(options) do |result|
end
```
It make no sense to add similar feature to `#publish_topic` or `#publish_messages`.
=> Enable waiting for response for #publish_message

lib/manageiq/messaging/stomp/common.rb, lib/manageiq/messaging/stomp/queue.rb, lib/manageiq/messaging/stomp/topic.rb
1. Fix a typo for correlation_ref
2. Limit the length of message body to be logged.
We have the use case for publishing large size message. As a quick and temporary solution I simply truncate the logging of message body to 100 characters. A more sophisticated handling including filtering sensitive data in a message body may need.
=> Fix a typo for correlation_ref

lib/manageiq/messaging/stomp/common.rb, spec/manageiq/messaging/stomp/client_spec.rb
Queue messages with the same `group_name` will be consumed by the same consumer.
Allow to add `:group_name => <name>` to `client.publish_message(options)` option list.
=> Add :group_name option

lib/manageiq/messaging/stomp/background_job.rb, lib/manageiq/messaging/stomp/queue.rb, lib/manageiq/messaging/stomp/topic.rb
For STOMP the stomp gem uses a dedicated thread for subscribing and consuming messages. If the user consumer block raises an error it will cause the thread to die silently without the main/worker thread knowing. The minimum we must do it to rescue any error and log it. Beyond that we can have three options:
1. Re-reaise the error so the consumer thread will die. It is up to the worker thread whether to abort by setting `Thread::abort_on_exception`
2. Write to an error flag and allow the consumer thread to die. The worker thread will periodically check for the error flag and decide how to proceed.
3. Consume the error and let the consumer to continue.
I prefer option 2, but it requires that we add a new healthiness check method to the client interface. I will postpone the decision how to …
=> rescue and log consumer errors

lib/manageiq/messaging/stomp/client.rb, lib/manageiq/messaging/stomp/common.rb, spec/manageiq/messaging/stomp/client_spec.rb
Json is 95% faster than yaml. [[ref]](https://gist.github.com/kbrock/978baec148501587f8160864815c07ac)
Json has no native support for dates or symbols. But since our goal is to support multiple languages, this may be a good thing.
Not ready to make a complete break, but this allows us to experiment with the various encoding.
It also allows a developer to add a custom encoder when initializing the client.
~~This does require us to `require "json"` first.~~
=> allow yaml or json encoding

lib/manageiq/messaging/stomp/common.rb, spec/manageiq/messaging/stomp/client_spec.rb
By default messages are durable. Any undelivered messages are lost if the server interrupts or reboots.
This work is to make each message durable.
=> Make each message durable

lib/manageiq/messaging.rb, lib/manageiq/messaging/client.rb, lib/manageiq/messaging/kafka.rb, lib/manageiq/messaging/kafka/background_job.rb, lib/manageiq/messaging/kafka/client.rb, lib/manageiq/messaging/kafka/common.rb, lib/manageiq/messaging/kafka/queue.rb, lib/manageiq/messaging/kafka/topic.rb, lib/manageiq/messaging/stomp.rb, manageiq-messaging.gemspec, spec/manageiq/messaging/kafka/client_spec.rb
This work adds Kafka as one of supported underlying messaging system.
This initial work only support broadcast/subscribe (topic) model. Point-to-point messaging (queue) implementation may be added in the future. However p2p messaging can be already done by using the implemented broadcast/subscribe model.
~~To use the client as a subscriber, the initialization options must include `group_ref`~~. If multiple clients join different groups and subscribe to the topic, every group will receive all the messages. This is the broadcast/subscribe model.
If there is only one group for a given topic, it works like a p2p communication. If multiple clients join the same group, the clients will consume messages in a load-balanced way.
With updated commit, both p2p and broadcast are now supported, and …
=> Support Kafka publish/subscribe_topic

lib/manageiq/messaging/common.rb, lib/manageiq/messaging/kafka/client.rb, lib/manageiq/messaging/kafka/common.rb, lib/manageiq/messaging/kafka/queue.rb, lib/manageiq/messaging/kafka/topic.rb, lib/manageiq/messaging/stomp/common.rb, spec/manageiq/messaging/kafka/client_spec.rb
- Create separate topic if affinity is needed
- Use `:group_name` to group messages
- Move metadata to headers
- Move shared code to common
@agrare please review and test. For your existing code you only need to change key `:affinity` to `:group_name` in `options`. 
`group_name` is already used in the Artemis for the same purpose. We'd better to use the same key.
=> A few refactorings for Kafka

examples/message.rb, lib/manageiq/messaging/client.rb, lib/manageiq/messaging/common.rb, lib/manageiq/messaging/kafka/client.rb, lib/manageiq/messaging/kafka/common.rb, lib/manageiq/messaging/kafka/queue.rb, lib/manageiq/messaging/kafka/topic.rb, lib/manageiq/messaging/stomp/queue.rb, lib/manageiq/messaging/stomp/topic.rb, spec/manageiq/messaging/kafka/client_spec.rb, spec/manageiq/messaging/stomp/client_spec.rb
This work allows to configure how to commit/ack subscribed messages.
Previously all Kafka messages are always auto committed. Artemis STOMP messages are auto committed for event/topic type; manually committed for message type.
Now any message by default is always auto committed. This is feature is turned off if subscribe `options[:auto_ack]` is `false`. Then the user block can decide where to ack the commit, before or after the message is processed.
=> Default auto commit subscribed messages, but allow to be turned off

lib/manageiq/messaging/kafka/client.rb, lib/manageiq/messaging/kafka/queue.rb, spec/manageiq/messaging/kafka/client_spec.rb
The default value of 10MB is too big, it's causing our app to
shoot to 400-500MB.
=> Allow to pass max_bytes to each_batch method

README.md, examples/message.rb, lib/manageiq/messaging/client.rb, lib/manageiq/messaging/kafka/common.rb, lib/manageiq/messaging/kafka/queue.rb, lib/manageiq/messaging/received_message.rb, lib/manageiq/messaging/stomp/queue.rb, lib/manageiq/messaging/stomp/topic.rb, spec/manageiq/messaging/kafka/client_spec.rb, spec/manageiq/messaging/stomp/client_spec.rb
Instead of requiring the caller call client.ack(msg.ack_ref) simply
allow calling ack on the message directly.
E.g.:
client.ack(msg.ack_ref)
becomes
msg.ack
=> Add an #ack method to ReceivedMessage

lib/manageiq/messaging/kafka/client.rb, lib/manageiq/messaging/kafka/common.rb, lib/manageiq/messaging/kafka/queue.rb, lib/manageiq/messaging/kafka/topic.rb
Add an option to control the kafka session_timeout which defaults to 30
seconds and has a maximum by default of 5 minutes.  This maximum can be
updated by changing group.max.session.timeout.ms on the broker.
=> Add an optional session_timeout option for kafka

CHANGES, lib/manageiq/messaging/version.rb
Changes:
* Add an #ack method to a ReceivedMessage to simplify manual acknowledgements
* Allow caller to provide a session_timeout to kafka consumers, default
of 30sec
=> Release v0.1.4

README.md, lib/manageiq/messaging/client.rb, lib/manageiq/messaging/kafka/common.rb, lib/manageiq/messaging/kafka/queue.rb, lib/manageiq/messaging/received_message.rb, lib/manageiq/messaging/stomp/common.rb, lib/manageiq/messaging/stomp/queue.rb, lib/manageiq/messaging/stomp/topic.rb, manageiq-messaging.gemspec, spec/manageiq/messaging/kafka/client_spec.rb
There are some cases where extra headers should be added to the message
and there currently is no interface to be able to do that.
This adds the ability to pass other arbitrary headers in to
publish_topic/publish_message.
=> Allow extra headers to be passed with the message

lib/manageiq/messaging/common.rb, lib/manageiq/messaging/kafka/queue.rb, lib/manageiq/messaging/stomp/queue.rb, lib/manageiq/messaging/stomp/topic.rb
An efford of improving error handling for subscribing. When a message is received we first try to decode the body and then yield to caller to process the message. It is the gem's responsibility not to raise an error or to crash the listener thread. It is the caller's responsibility not to raise an error during the process. If it does happen, the gem should not consume the error. PR #44 already re-raise the error for Kafka events. We now apply the same logic to all other subscribing types.
=> Catch decoding parsing error

.travis.yml
we no longer need `sudo: false` per https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration
=> remove sudo: false from .travis.yml

lib/manageiq/messaging/kafka/client.rb, spec/manageiq/messaging/kafka/client_spec.rb
This is part of the solution for:
https://github.com/ManageIQ/manageiq-appliance-build/issues/456
Different security protocols will have different options. This PR will support this by passing
all provided options to `::Rdkafka::Config.new`
=> Config kafka with all provided options

lib/manageiq/messaging/kafka/client.rb, spec/manageiq/messaging/kafka/client_spec.rb
`:username` and `:password` are standard options that should be able to be passed in to the generic `ManageIQ::Messaging::Client.open()` without having to get into kafka specifics like `:"sasl.username"` or `:"sasl.password"`
=> Convert standard options to sasl parameters

README.md, lib/manageiq/messaging.rb, lib/manageiq/messaging/client.rb, lib/manageiq/messaging/kafka/common.rb, lib/manageiq/messaging/kafka/queue.rb, lib/manageiq/messaging/kafka/topic.rb, lib/manageiq/messaging/stomp/topic.rb, spec/manageiq/messaging/client_spec.rb
Kafka allows for far more efficient publication of multiple messages by producing many messages then waiting on them after publication.
=> Add a bulk publish option to the `#publish_topic` API

.github/workflows/ci.yaml, spec/manageiq/messaging/kafka/client_spec.rb
made the kwargs fixes.
added ruby 3.0 to the matrix.
Fixes #70
=> add ruby 3.0 support

lib/manageiq/messaging/kafka/common.rb
The rdkafka producer takes kwargs (https://github.com/appsignal/rdkafka-ruby/blob/main/lib/rdkafka/producer.rb#L76) and we were passing a hash:
```
rdkafka-0.12.0/lib/rdkafka/producer.rb:74:in `produce': wrong number of arguments (given 1, expected 0; required keyword: topic) (ArgumentError)
from /home/grare/adam/src/manageiq/manageiq-messaging/lib/manageiq/messaging/kafka/common.rb:26:in `raw_publish'
from /home/grare/adam/src/manageiq/manageiq-messaging/lib/manageiq/messaging/kafka/topic.rb:13:in `block in publish_topic_impl'
from /home/grare/adam/src/manageiq/manageiq-messaging/lib/manageiq/messaging/kafka/topic.rb:13:in `collect'
from /home/grare/adam/src/manageiq/manageiq-messaging/lib/manageiq/messaging/kafka/topic.rb:13:in `publish_topic_impl'
from …
```
=> Fix kafka publish_topic on ruby3

CHANGELOG.md, lib/manageiq/messaging/kafka/common.rb, lib/manageiq/messaging/kafka/queue.rb, lib/manageiq/messaging/kafka/topic.rb
Add an option to Kafka subscribe_messages and subscribe_topic to wait for topic creation with increasing backoff retry.
=> Add wait_for_topic option to Kafka

CHANGELOG.md, lib/manageiq/messaging/client.rb, lib/manageiq/messaging/kafka/client.rb, lib/manageiq/messaging/stomp/client.rb, spec/manageiq/messaging/kafka/client_spec.rb
Don't require users to pass in librdkafka specific options in order to use SSL / Certificate Authorities
Previously:
```
ManageIQ::Messaging.open(
:protocol            => 'Kafka',
:host                => 'localhost',
:port                => 9092,
:"sasl.username"     => 'user',
:"sasl.password"     => 'password',
:"security.protocol" => 'SASL_SSL',
:"ssl.ca.location"   => '/path/to/cert'
)
```
Now:
```
ManageIQ::Messaging.open(
:protocol   => 'Kafka',
:host       => 'localhost',
:port       => 9092,
:username   => "user",
:password   => 'password',
:ssl        => true,
:ca_file    => '/path/to/cert'
)
```
=> Add ssl and ca_file options to Client.open()

lib/manageiq/messaging/kafka/client.rb
- keystore config options necessary for Kafka SSL on podified
- see: https://github.com/confluentinc/librdkafka/blob/master/CONFIGURATION.md
Depends on:
Ref:
- https://github.com/ManageIQ/manageiq-pods/issues/789
@miq-bot assign @agrare 
@miq-bot add_label enhancement
=> Add Kafka SSL keystore options to client

lib/manageiq/messaging/kafka/client.rb
- Added option to specify sasl mechanism allowing for another mechanism to be used in podified i.e. `SCRAM-SHA-512` and will default to PLAIN if not provided. This allows us to support other SASL mechanisms on podified without having to implement changes on the appliance side to support the same mechanism 
- Turns out keystores aren't needed because they are only used for mTLS authentication. Since we are using SASL for authentication a client side keystore isn't needed because you can only have one authentication method: SASL or mTLS. For a better explanation see https://docs.confluent.io/platform/current/kafka/configure-mds/mutual-tls-auth-rbac.html#authentication
TODO:
Depends on:
@miq-bot assign @agrare 
@miq-bot add_reviewer @Fryguy 
@miq-bot add_labels enhancement
=> Kafka client options updates

lib/manageiq/messaging/kafka/common.rb
Message hashes can also be received with string keys instead of symbols, this was causing `nil` values to be retrieved from the header hash when using the `.values_at` method, resulting in failures when using these values to invoke methods later on
For example (notice how ems/sender and event types are empty in logging):
```
Nov 28 16:00:37 agrare-im-rhv.rtp.raleigh.ibm.com evm[85076]:  INFO -- evm: MIQ(MiqQueue.process_topic_message) Event received: topic(manageiq.ems), event({"event_type"=>"USER_ADD_DISK_TO_VM", "source"=>"RHEVM", "message"=>"Add-Disk operation of Dave_Test0), sender(), type()
Nov 28 16:00:37 agrare-im-rhv.rtp.raleigh.ibm.com evm[85076]:  INFO -- evm: MIQ(MiqQueue.process_topic_message) Event processed
Nov 28 16:00:37 agrare-im-rhv.rtp.raleigh.ibm.com evm[85076]: DEBUG …
```
=> Handle headers with string keys

.github/workflows/ci.yaml, Gemfile, manageiq-messaging.gemspec
Allow rails 7 gems in gemspec
Note, this PR drops ruby 2.6 from tests.
Ruby 2.6 is EOL and not supported by rails 7.  If we really need it, can
test ruby 2.6 against rails < 7.
=> Allow rails 7 gems in gemspec

lib/manageiq/messaging/kafka/client.rb
This method uses the rdkafka admin API to retrieve metadata from the kafka server. This is a good way to perform health checks since if the kafka server is down, this will return an error instead. 
@miq-bot assign @agrare 
@miq-bot add_reviewer @agrare 
@miq-bot add_label enhancement
=> Fix Kafka Client List Topics Method

lib/manageiq/messaging/kafka/client.rb, lib/manageiq/messaging/kafka/common.rb
The rdkafka admin client connection should be closed similar to how its done for producers/consumers to avoid unwanted behaviour
@miq-bot assign @agrare 
@miq-bot add_reviewer @agrare 
@miq-bot add_label bug
=> Close Kafka admin client connection

.github/workflows/ci.yaml, Gemfile, manageiq-messaging.gemspec
Ensure we're testing and supporting community supported
versions.
Drop:
* ruby 2.7
* rails 6.0
* rails 6.1
Add:
* ruby 3.2
* ruby 3.3
* rails 7.1
* rails 7.2
Note: ruby 3.0 is not difficult to keep maintaining for now but it's on the chopping block.
=> Update ruby rails dependencies (breaking change)

lib/manageiq/messaging/client.rb, spec/manageiq/messaging/client_spec.rb
If a protocol option isn't passed we shouldn't just default to Stomp as that can cause unexpected issues if protocol is missing but the user is expecting to use kafka.
=> Don't default to protocol=Stomp
